"""
Django settings for pet_clinic_insurance_service project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
import boto3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ico9wd)8v2jqn*huz=cecidbyjjbf!7j*fx&@$c15=a(1p+w$)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "service"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pet_clinic_insurance_service.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pet_clinic_insurance_service.wsgi.application"


# Get secret name and region from environment or use defaults
SECRET_NAME = os.environ.get('SECRET_NAME', 'petclinic-python-dbsecret')
REGION = os.environ.get('REGION', 'us-east-1')

def get_secret_value(secret_name: str, region_name: str) -> str:
    """
    Retrieve a secret string from AWS Secrets Manager.
    """
    client = boto3.client('secretsmanager', region_name=region_name)
    response = client.get_secret_value(SecretId=secret_name)
    return response['SecretString'] 


env_db_password = os.environ.get('DB_USER_PASSWORD')

if env_db_password:
    DB_PASSWORD = env_db_password
else:
    # Retrieve from Secrets Manager
    try:
        DB_PASSWORD = get_secret_value(SECRET_NAME, REGION)
        print(f"Retrieved secret '{SECRET_NAME}' from AWS Secrets Manager {DB_PASSWORD}")
    except Exception as e:
        # Print the error
        print(f"Error retrieving secret '{SECRET_NAME}' from AWS Secrets Manager: {e}", file=sys.stderr)


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    # local database - sqlite3
    "local": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "postgresql":{
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME'),
        "USER": os.environ.get('DB_USER'),
        "PASSWORD": DB_PASSWORD,
        "HOST": os.environ.get("DB_SERVICE_HOST"),
        "PORT": os.environ.get("DB_SERVICE_PORT"),
        # CRITICAL: Add connection pooling and performance optimizations
        "OPTIONS": {
            # Connection pool settings to prevent database overload
            "MAX_CONNS": 20,
            "MIN_CONNS": 5,
            # Query optimization settings
            "connect_timeout": 30,
            "options": "-c default_transaction_isolation=read_committed -c statement_timeout=60000"
        },
        # Connection pool configuration
        "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        "CONN_HEALTH_CHECKS": True,  # Enable connection health checks
        # Performance settings
        "ATOMIC_REQUESTS": False,  # Disable atomic requests for better performance
        "AUTOCOMMIT": True,  # Enable autocommit for better performance
    }
}

default_database = os.environ.get('DATABASE_PROFILE', 'local')
DATABASES['default'] = DATABASES[default_database]

# Add database connection pooling for production
if default_database == 'postgresql':
    # Enable connection pooling with pgbouncer-like settings
    DATABASES['default']['OPTIONS'].update({
        # Connection management
        'MAX_CONNS': 20,
        'MIN_CONNS': 5,
        # Query timeout settings to prevent long-running queries
        'connect_timeout': 30,
        'options': '-c default_transaction_isolation=read_committed -c statement_timeout=60000 -c idle_in_transaction_session_timeout=300000'
    })

# Cache configuration for better performance
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'insurance-service-cache',
        'TIMEOUT': 300,  # 5 minutes
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# Session configuration for better performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        # Add database query logging for performance monitoring
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING',  # Only log slow queries and errors
            'propagate': False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework configuration for better performance
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,  # Limit page size to prevent large queries
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}